#spring.application.name=QuoraApp
#server.port=3000
#

spring :
  application:
    name : QuoraApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database : quora_db
      auto-index-creation: true

redis:
  host: localhost
  port: 6379


server:
  port : 3000


elasticsearch:
  uris : http://localhost:9200


